// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewRecord struct {
	ID        string `json:"ID"`
	Title     string `json:"title"`
	Content   string `json:"Content"`
	Views     int    `json:"Views"`
	Timestamp int    `json:"Timestamp"`
}

type Record struct {
	ID        string `json:"ID"`
	Title     string `json:"title"`
	Content   string `json:"Content"`
	Views     int    `json:"Views"`
	Timestamp int    `json:"Timestamp"`
}
