# Simple Kubernetes Pod to deploy the app contained in nigelpoulton/getting-started-k8s:1.0
apiVersion: v1
kind: Pod
metadata:
  name: sample-go
  labels:
    app: web
spec:
  containers:
    - name: web-ctr
      image: sample-go:v1.1
      imagePullPolicy: Never
      ports:
        - containerPort: 3000
